package com.minesweeper.api.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.minesweeper.api.dto.MineSweeperRequest;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

import java.util.Date;
import java.util.List;

@DynamoDBTable(tableName = "Minesweeper-Api.Games")
@Data
@AllArgsConstructor
@Builder
public class MineSweeper {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @DynamoDBHashKey(attributeName = "userId")
    private String userId;

    @DynamoDBHashKey(attributeName = "metadata")
    private MineSweeperRequest metadata;

    @DynamoDBHashKey(attributeName = "cells")
    private List<Cell> cells;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBHashKey(attributeName = "status")
    private Status status;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBHashKey(attributeName = "timePaused")
    @Builder.Default
    private long timePaused = 0L;

    @DynamoDBHashKey(attributeName = "createDate")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createDate;

    @DynamoDBHashKey(attributeName = "lastUpdate")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date lastUpdate;

}
